saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.product_detail, name='product-detail'),
    url(r'^(?P<pk>[0-9]+)/publish/$', views.product_toggle_is_published,
        name='product-publish'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),
    url(r'^add/(?P<class_pk>[0-9]+)/$',
        views.product_create, name='product-add'),

    url(r'^classes/$',
        views.product_class_list, name='product-class-list'),
    url(r'^classes/add/$',
        views.product_class_create, name='product-class-add'),
    url(r'^classes/(?P<pk>[0-9]+)/update/$',
        views.product_class_edit, name='product-class-update'),
    url(r'^classes/(?P<pk>[0-9]+)/delete/$',
        views.product_class_delete, name='product-class-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_details, name='variant-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$',
        views.variant_images, name='variant-images'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='variant-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/$',
        views.stock_details, name='variant-stock-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/update/$',
        views.stock_edit, name='variant-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='variant-stock-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/$', views.product_images,
        name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/reorder/$',
        views.ajax_reorder_product_images, name='product-images-reorder'),
    url(r'^(?P<product_pk>[0-9]+)/images/upload/$',
        views.ajax_upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_detail, name='product-attribute-detail'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),

    url(r'stocklocations/$', views.stock_location_list,
        name='product-stock-location-list'),
    url(r'stocklocations/add/$', views.stock_location_edit,
        name='product-stock-location-add'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/$', views.stock_location_edit,
        name='product-stock-location-edit'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/delete/$',
        views.stock_location_delete, name='product-stock-location-delete'),
]

saleor/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category'),
    url(r'(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/add/$',
        views.product_add_to_cart, name="add-to-cart"),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/product/views.py
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST

from ...core.utils import get_paginator_items
from ...product.models import (
    Product, ProductAttribute, ProductClass, ProductImage, ProductVariant,
    Stock, StockLocation)
from ...product.utils import get_availability
from ..views import staff_member_required, superuser_required
from ...settings import DASHBOARD_PAGINATE_BY
from . import forms


@superuser_required
def product_class_list(request):
    classes = ProductClass.objects.all().prefetch_related(
        'product_attributes', 'variant_attributes')
    form = forms.ProductClassForm(request.POST or None)
    if form.is_valid():
        return redirect('dashboard:product-class-add')
    classes = get_paginator_items(
        classes, DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    classes.object_list = [
        (pc.pk, pc.name, pc.has_variants, pc.product_attributes.all(),
         pc.variant_attributes.all())
        for pc in classes.object_list]
    ctx = {'form': form, 'product_classes': classes}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/list.html',
        ctx)


@superuser_required
def product_class_create(request):
    product_class = ProductClass()
    form = forms.ProductClassForm(request.POST or None,
                                  instance=product_class)
    if form.is_valid():
        product_class = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product type %s') % product_class
        messages.success(request, msg)
        return redirect('dashboard:product-class-list')
    ctx = {'form': form, 'product_class': product_class}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/form.html',
        ctx)


@superuser_required
def product_class_edit(request, pk):
    product_class = get_object_or_404(
        ProductClass, pk=pk)
    form = forms.ProductClassForm(request.POST or None,
                                  instance=product_class)
    if form.is_valid():
        product_class = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated product type %s') % product_class
        messages.success(request, msg)
        return redirect('dashboard:product-class-update', pk=pk)
    ctx = {'form': form, 'product_class': product_class}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/form.html',
        ctx)


@superuser_required
def product_class_delete(request, pk):
    product_class = get_object_or_404(ProductClass, pk=pk)
    if request.method == 'POST':
        product_class.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message',
                'Deleted product type %s') % product_class)
        return redirect('dashboard:product-class-list')
    ctx = {'product_class': product_class,
           'products': product_class.products.all()}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/modal/confirm_delete.html',
        ctx)


@staff_member_required
@permission_required('product.view_product')
def product_list(request):
    products = Product.objects.prefetch_related('images')
    products = products.order_by('name')
    product_classes = ProductClass.objects.all()
    form = forms.ProductClassSelectorForm(
        request.POST or None, product_classes=product_classes)
    if form.is_valid():
        return redirect(
            'dashboard:product-add', class_pk=form.cleaned_data['product_cls'])
    products = get_paginator_items(
        products, DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    ctx = {
        'form': form, 'products': products, 'product_classes': product_classes}
    return TemplateResponse(request, 'dashboard/product/list.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def product_create(request, class_pk):
    product_class = get_object_or_404(ProductClass, pk=class_pk)
    create_variant = not product_class.has_variants
    product = Product()
    product.product_class = product_class
    product_form = forms.ProductForm(request.POST or None, instance=product)
    if create_variant:
        variant = ProductVariant(product=product)
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if product_form.is_valid() and not variant_errors:
        product = product_form.save()
        if create_variant:
            variant.product = product
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product %s') % product
        messages.success(request, msg)
        return redirect('dashboard:product-detail', pk=product.pk)
    ctx = {
        'product_form': product_form, 'variant_form': variant_form,
        'product': product}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.view_product')
def product_detail(request, pk):
    products = Product.objects.prefetch_related(
        'variants__stock', 'images',
        'product_class__variant_attributes__values').all()
    product = get_object_or_404(products, pk=pk)
    variants = product.variants.all()
    images = product.images.all()
    availability = get_availability(product)
    sale_price = availability.price_range
    gross_price_range = product.get_gross_price_range()

    # no_variants is True for product classes that doesn't require variant.
    # In this case we're using the first variant under the hood to allow stock
    # management.
    no_variants = not product.product_class.has_variants
    only_variant = variants.first() if no_variants else None
    if only_variant:
        stock = only_variant.stock.all()
    else:
        stock = Stock.objects.none()
    ctx = {
        'product': product, 'sale_price': sale_price, 'variants': variants,
        'gross_price_range': gross_price_range, 'images': images,
        'no_variants': no_variants, 'only_variant': only_variant,
        'stock': stock}
    return TemplateResponse(request, 'dashboard/product/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def product_toggle_is_published(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_published = not product.is_published
    product.save(update_fields=['is_published'])
    return JsonResponse(
        {'success': True, 'is_published': product.is_published})


@staff_member_required
@permission_required('product.edit_product')
def product_edit(request, pk):
    product = get_object_or_404(
        Product.objects.prefetch_related('variants'), pk=pk)

    edit_variant = not product.product_class.has_variants
    form = forms.ProductForm(request.POST or None, instance=product)

    if edit_variant:
        variant = product.variants.first()
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if form.is_valid() and not variant_errors:
        product = form.save()
        if edit_variant:
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated product %s') % product
        messages.success(request, msg)
        return redirect('dashboard:product-detail', pk=product.pk)
    ctx = {'product': product, 'product_form': form,
           'variant_form': variant_form}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        messages.success(
            request,
            pgettext_lazy('Dashboard message', 'Deleted product %s') % product)
        return redirect('dashboard:product-list')
    return TemplateResponse(
        request,
        'dashboard/product/modal/confirm_delete.html',
        {'product': product})


@staff_member_required
@permission_required('product.view_stock_location')
def stock_details(request, product_pk, variant_pk, stock_pk):
    product = get_object_or_404(Product, pk=product_pk)
    variant = get_object_or_404(product.variants, pk=variant_pk)
    stock = get_object_or_404(variant.stock, pk=stock_pk)
    ctx = {'stock': stock, 'product': product, 'variant': variant}
    return TemplateResponse(
        request,
        'dashboard/product/stock/detail.html',
        ctx)


@staff_member_required
@permission_required('product.edit_stock_location')
def stock_edit(request, product_pk, variant_pk, stock_pk=None):
    product = get_object_or_404(Product, pk=product_pk)
    variant = get_object_or_404(product.variants, pk=variant_pk)
    if stock_pk:
        stock = get_object_or_404(variant.stock, pk=stock_pk)
    else:
        stock = Stock()
    form = forms.StockForm(
        request.POST or None, instance=stock, variant=variant)
    if form.is_valid():
        form.save()
        messages.success(
            request, pgettext_lazy('Dashboard message', 'Saved stock'))
        return redirect(
            'dashboard:variant-details', product_pk=product.pk,
            variant_pk=variant.pk)
    ctx = {'form': form, 'product': product,

templates/dashboard/product/product_image/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% if product_image.pk %}
    {% trans "Edit - Image" context "Image form text" %}
  {% else %}
    {% trans "Add image" context "Image form text" %}
  {% endif %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-store body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:product-detail" pk=product.pk as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-detail" pk=product.pk %}" class="breadcrumbs--ellipsed-item">
        {{ product }}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-detail" pk=product.pk %}" class="breadcrumb">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    {% if product_image.pk %}
      <li>
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Image" context "Image form text" %}
        </span>
      </li>
      <li>
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Edit" context "Image form text" %}
        </span>
      </li>
    {% else %}
      <li>
        <span class="hide-on-med-and-down">
          {% trans "Add image" context "Image form breadcrumbs" %}
        </span>
        <span class="hide-on-large-only breadcrumbs--ellipsed-item">
          {% blocktrans trimmed context "Image form breadcrumbs"  %}
            Add image for {{ product }}
          {% endblocktrans %}
        </span>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 m9">
      <div class="card">
        <form method="post" enctype="multipart/form-data">
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              <div class="col s12 m8">
                <div class="row">
                  {{ form.image|materializecss }}
                </div>
                {% if product_image.pk %}
                  <p class="no-margin">
                    {% trans "Pick the most relevant part of the image using the red circle." context "Image form text" %}
                  </p>
                {% endif %}
              </div>
            </div>
            <div class="row">
              {{ form.alt|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            {% if product_image.pk %}
              <a href="{% url "dashboard:product-image-list" product.pk %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect waves-light">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url "dashboard:product-image-list" product.pk %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect waves-light">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3 help-box"></div>
  </div>
{% endblock %}

templates/dashboard/product/product_image/list.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}
  {% trans "Images" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-list" %}" class="breadcrumb">
        {% trans "Products" context "Dashboard products list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-list" %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <a href="{% url "dashboard:product-detail" product.pk %}">{{ product }}</a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">{% trans "Images" %}</span>
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div id="images" class="tab-content">
      <form action="{% url 'dashboard:product-images-upload' product_pk=product.pk %}" class="dropzone" id="product-image-form" novalidate>
        <div class="dz-message"></div>
        {% csrf_token %}
        <div class="row">
          <ul class="product-gallery" id="product-gallery" data-post-url="{% url 'dashboard:product-images-reorder' product_pk=product.pk %}">
            {% if images %}    
              {% for image in images %}
                <li class="col s6 m3 product-gallery-item" data-id="{{ image.pk }}">
                  <div class="row">
                    <div class="card">
                      <div class="card-image product-gallery-item-image">
                        <img class="responsive-img"
                             src="{{ image.image.crop.255x255 }}"
                             srcset="{{ image.image.crop.255x255 }} 1x, {{ image.image.crop.510x510 }} 2x"
                             alt="">
                      </div>
                      <div class="card-content">
                        <span class="product-gallery-item-title card-title black-text" title="{{ image.alt }}">
                          {% if image.alt %}
                            {{ image.alt }}
                          {% else %}
                            <span class="grey-text">
                              {% trans "No description" context "Image card text" %}
                            </span>
                          {% endif %}
                        </span>
                      </div>
                      <div class="sortable__drag-area"></div>
                      <div class="card-action">
                        <a class="btn btn-flat" href="{% url 'dashboard:product-image-update' product_pk=product.pk img_pk=image.pk %}">
                          {% trans "Edit" context "Dashboard edit action" %}
                        </a>
                        <a href="#base-modal" class="btn btn-flat modal-trigger-custom" data-href="{% url 'dashboard:product-image-delete' product_pk=product.pk img_pk=image.pk %}">
                          {% trans "Delete" context "Dashboard delete action" %}
                        </a>
                      </div>
                    </div>
                  </div>
                </li>
              {% endfor %}
            {% else %}
              <div class="sortable__drag-area"></div>
            {% endif %}
          </ul>
        <div class="col s6 m3 product-gallery-item dropzone-message">
          <div class="row">
            <span class="product-gallery-item-title product-gallery-item-title--noclip card-title black-text">
              <span class="grey-text hide-on-med-and-down">
                {% trans "Drop images here to upload" context "Image gallery upload box text" %}
              </span>
            </span>
          </div>
        </div>
      </div>
      </form>
      <script type="application/template" id="template">
        <li class="col s6 m3 product-gallery-item dz-preview dz-file-preview" data-id="{{ image.pk }}">
          <div class="row">
            <div class="card">
              <div class="card-image product-gallery-item-image">
                <img data-dz-thumbnail />
              </div>
              <div class="dz-progress">
                <span class="dz-upload" data-dz-uploadprogress></span>
              </div>
              <div class="card-content">
                <span class="product-gallery-item-title card-title black-text">
                  <span class="grey-text">
                    {% trans "No description" context "Empty image gallery message" %}
                  </span>
                </span>
              </div>
              <div class="sortable__drag-area"></div>
              <div class="card-action">
                <a class="btn btn-flat card-action-edit" href="{% url 'dashboard:product-image-update' product_pk=product.pk img_pk=0 %}">
                  {% trans "Edit" context "Dashboard edit action" %}
                </a>
                <a href="#base-modal" class="btn btn-flat card-action-delete modal-trigger-custom"
                data-href="{% url 'dashboard:product-image-delete' product_pk=product.pk img_pk=0 %}">
                  {% trans "Delete" context "Dashboard delete action" %}
                </a>
              </div>
            </div>
          </div>
        </li>
      </script>
    </div>
    <div class="fixed-action-btn">
      <a class="btn-fab btn-floating btn-large waves-effect waves-light teal" id="images-btn" href="{% url 'dashboard:product-image-add' product_pk=product.pk %}" title="{% trans "Add image" context "Add image button text" %}">
        <svg data-src="{% static "dashboard/images/add.svg" %}" />
      </a>
    </div>
{% endblock %}